### ISSUE TITLE
Hardcoded Private Key

### ISSUE THREAD

**Issue by sihoang** [kardiachain/go-kardia#111]
I was wondering why the private key is hardcoded in the main config
https://github.com/kardiachain/go-kardia/blob/master/cmd/cfg/kai_config.yaml#L19

```
 P2P:
    PrivateKey: 8843ebcb1021b00ae9a644db6617f9c6d870e5fd53624cefe374c1d2d710fd06
    ListenAddress: tcp://0.0.0.0:3000
    MaxPeers: 25
```
